version: '3'
services:
  proxy:
    container_name: proxy
    build: ./proxy
    ports:
      - "8081:8080"
    links:
      - "api"

  api:
    build: ./grpcweb
    container_name: server
    tty: true
    stdin_open: true
    working_dir: "/go/src" 
    volumes:
      - ./src/main.go:/go/src/main.go
      - ./src/test:/go/src/test
      - ./src/server:/go/src/server
      - ./src/model:/go/src/model
      - ../protoc-gen-docker/src/go/:/go/src/proton/